### PR TITLE
Semi-Comprehensive List of All Members

### PR DESCRIPTION
**Pull request by amiruqdah**
Read [this](http://goo.gl/QwG6a8) first.

I made a small(and broken) Python [script](https://gist.github.com/amiruqdah/5e8bebbd592491a6543f) that pulled member information from the HSHacker and compiled it into the members.csv file. I alphabetized the file using `sort` .

I ran into some problems regarding grabbing certain links, but at least we've got everyone's name now. At least I think we do...

### CODE REVIEW

**Comment by zachlatta** [comment]
Awesome! Can you merge this with the existing CSV so we don't overwrite existing data?

**Comment by amiruqdah** [comment]
Hand merged everything. Found a few people that were no longer in the group anymore, so their names aren't listed. A few people changed their names on FB, but I was able to track em down and put in updated information. Anywho, it's done! :fire:

**Comment by zachlatta** [comment]
Awesome! :shipit:

One last thing—can you squash your commits into a single commit ready for merge? See https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes-optional for more details.

**Comment by amiruqdah** [comment]
I think I squashed it too much... :-1:  *sigh*

**Comment by amiruqdah** [comment]
Created a new pull request, instead of trying to fix this one. Git is confusing.

**Comment by zachlatta** [comment]
Haha, alright! Sounds good.

**Comment by zachlatta** [comment]
Awesome! Will try to get to it later today.

--
Zach Latta
Executive Director of hackEDU[https://hackedu.us/]
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by amiruqdah** [comment]
@zachlatta 

:+1: you're the best

**Pull request closed without merging**
