### PR TITLE
added all HSHacker participants to members.csv

### PR DESCRIPTION
**Pull request by amiruqdah**
New slate.

Ended up squashing my commits down too far, so I thought I'd start over without playing around with rebase :+1:

### CODE REVIEW

**Comment by zachlatta** [comment]
Awesome! Two more things:

* It'd be great if you could give the commit a more descriptive name
* Can you add a newline at the end of the file like how it was before?

**Comment by amiruqdah** [comment]
*sweats nervously*

Don't merge yet... I'm going to...attempt.. to...rebase...and not mess up this time. :fire: :fire_engine:

**Comment by amiruqdah** [comment]
@zachlatta 

Squashed(both literally and figuratively)!! Added a new line, and made the commit message more detailed :metal:

**Comment by zachlatta** [comment]
:shipit:

**Pull request merged**
